export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const INCREMENT_BY_VALUE = 'INCREMENT_BY_VALUE';
export const INIT_ARTICLES = 'INIT_ARTICLES';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
export const CHANGE_FILTER_DATE = 'CHANGE_FILTER_DATE';